version: '2'
services:
    edplattform-app:
        image: edplattform
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://edplattform-mysql:3306/edplattform?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    edplattform-mysql:
        extends:
            file: mysql.yml
            service: edplattform-mysql
